baseURL: https://jernejmysiteapp.netlify.app
languageCode: en
defaultContentLanguage: en
title: Stip
theme: stip-hugo
disableKinds:
  - page
  - section
  - taxonomy
  - taxonomyTerm
Author:
  bio: Jernej Baranja 
  name: My site:)
params:
  links:
    - icon: envelope
      iconset: fas
      title: E-mail
      url: mailto:jernej.baranja@gov.si
    - icon: linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/jernej-baranja-28063962/
    - icon: twitter
      title: Twitter
      url: https://twitter.com/jernejbaranja
